name: Update Submodule

on:
  push:
    paths:
      - 'doctest/**'

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v2
        with:
          repository: 'creatoroid/test'
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Update submodule
        run: |
          cd doctest
          git pull origin main
          cd ../

      - name: Commit and Push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add doctest
          git commit -m "Update doctest submodule to latest commit"
          git push
